docker_builder:
  name: Release Docker Image
  only_if: $CIRRUS_TAG != ''
  env:
    GITHUB_TOKEN: ENCRYPTED[!82ed873afdf627284305afef4958c85a8f73127b09978a9786ac521559630ea6c9a5ab6e7f8315abf9ead09b6eff6eae!]
  login_script:
    - echo $GITHUB_TOKEN | docker login ghcr.io -u fkorotkov --password-stdin
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  deploy_script: |
    docker buildx build --build-arg OPENJDK_TAG=$TAG_NAME \
      --push --platform linux/amd64,linux/arm64 \
      --tag ghcr.io/cirruslabs/jvm-grpc:$CIRRUS_TAG \
      .
